version: '3'
services:

  dormitorio:
    image: localhost:5000/python-worker
    build: ./python-worker
    environment:
      - cam=0
      - horas=$compose_horas
      - modo=$compose_modo
      - habitacion=dormitorio
      - start_script=start.sh
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net

  servidor-web-dormitorio:
    image: localhost:5000/web-server
    build: ./web-server
    environment:
      - habitacion=dormitorio
      - script=podes_paginaweb.py
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net



  cocina:
    image: localhost:5000/python-worker
    build: ./python-worker
    environment:
      - cam=1
      - horas=$compose_horas
      - modo=$compose_modo
      - habitacion=cocina
      - start_script=start.sh
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net

  servidor-web-cocina:
    image: localhost:5000/web-server
    build: ./web-server
    environment:
      - habitacion=cocina
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net



  distribuidor:
    image: localhost:5000/python-worker
    build: ./python-worker
    environment:
      - cam=2
      - horas=$compose_horas
      - modo=$compose_modo
      - habitacion=distribuidor
      - start_script=start.sh
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net

  servidor-web-distribuidor:
    image: localhost:5000/web-server
    build: ./web-server
    environment:
      - habitacion=distribuidor
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net



  salon:
    image: localhost:5000/python-worker
    build: ./python-worker
    environment:
      - cam=3
      - horas=$compose_horas
      - modo=$compose_modo
      - habitacion=salon
      - start_script=start.sh
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net

  servidor-web-salon:
    image: localhost:5000/web-server
    build: ./web-server
    environment:
      - habitacion=salon
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net



  TV:
    image: localhost:5000/python-worker
    build: ./python-worker
    environment:
      - cam=4
      - horas=$compose_horas
      - modo=$compose_modo
      - habitacion=TV
      - start_script=start.sh
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net

  servidor-web-TV:
    image: localhost:5000/web-server
    build: ./web-server
    environment:
      - habitacion=TV
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net



  recibidor:
    image: localhost:5000/python-worker
    build: ./python-worker
    environment:
      - cam=5
      - horas=$compose_horas
      - modo=$compose_modo
      - habitacion=recibidor
      - start_script=start.sh
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net

  servidor-web-recibidor:
    image: localhost:5000/web-server
    build: ./web-server
    environment:
      - habitacion=recibidor
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net



  aseo:
    image: localhost:5000/python-worker
    build: ./python-worker
    environment:
      - cam=6
      - horas=$compose_horas
      - modo=$compose_modo_aseo
      - habitacion=aseo
      - start_script=start_termal.sh
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net

  servidor-web-aseo:
    image: localhost:5000/web-server
    build: ./web-server
    environment:
      - habitacion=aseo
    volumes:
      - sshvolumen-web:/volume
    networks:
      - shared_net



  proxy:
    image: localhost:5000/proxy-server
    build: ./proxy-server
    ports:
      - 80:80
    depends_on:
      - servidor-web-dormitorio
      - servidor-web-cocina
      - servidor-web-distribuidor
      - servidor-web-salon
      - servidor-web-TV
      - servidor-web-recibidor
      - servidor-web-aseo
    networks:
      - shared_net

volumes:
  sshvolumen-web:
    external:
      name: volumen-web

networks:
  shared_net:
    external: true
